QT_TRANSLATE_NOOP("Data Visualization Tutorial", "marp: true")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "theme: uncover")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "paginate: true")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "style: |")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "section{")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "width: 32cm;")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "height: 19cm;")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "justify-content: flex-start;")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "}")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "section.lead h6 {text-align: bottom;}")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "section.lead header {font-weight: bold;}")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "3D Slicer")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Now the slice views are linked. If you click the")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "‘Toggle slice visibility in 3D view’")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "button.")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Then all slices will show up.")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Data Loading and Visualization Tutorial")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Tutorial Dataset")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Please download the following datasets:")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "https://github.com/PerkLab/PerkLabBootcamp/raw/master/Data/VisualizationTutorial_HeadScene.mrb")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Main user interface")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Load Sample MRI Data")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Load Sample MRI Data")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Load Sample MRI Data")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "The axial, sagittal, and coronal views automatically show  the loaded volume")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Adjust window/level")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Switch to window/level mouse mode")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Adjust window/level")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Adjust window/level (brightness/contrast) using the left mouse button on a slice view")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Switch back to view/transform mode")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Maximize view")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Slice view options")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Position your mouse cursor over the pin icon to display the slice view toolbar")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Slice view options")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Once the slice viewer toolbar is shown, click on the “>>”.")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Show ruler")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Rotate to volume plane")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Often, MRI volumes are not axis-aligned. To show the true axial view, click the")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "‘Rotate to volume plane’")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "button.")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Note: This image will not be affected, but many DICOM MR images need to be aligned.")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Switch to conventional layout")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Link views")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "After linking views, if any setting is changed in a 2D view, all others follow.")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Show slices in 3D")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Now the slice views are linked. If you click the")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "‘Toggle slice visibility in 3D view’")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "button, then all slices will show up.")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Show slices in 3D")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "All three anatomical slices are shown in the 3D view.")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Navigating the 3D view")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Use the left mouse button to")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "rotate")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", ", and the right mouse button to")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "zoom")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "in and out.")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Close the scene")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Part 2: 3D visualization of surface models of the brain")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Load tutorial scene")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Drag and drop the file VisualizationTutorial_HeadScene.mrb into Slicer, then click")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "OK")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", ".")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Center view")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Click on the small box icon to center the view, in 3D or in 2D")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Explore loaded data")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "You can use the module list, or the favorite module toolbar to switch to the")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Data module")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Explore loaded data")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "The Data module shows all the data in the scene.")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "The data items (“nodes”) can be shown/hidden, renamed, deleted, cloned, etc.")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "Hide the")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "‘skin’")
QT_TRANSLATE_NOOP("Data Visualization Tutorial", "model by clicking the eye icon.")
