QT_TRANSLATE_NOOP::tr("marp: true")
QT_TRANSLATE_NOOP::tr("theme: uncover")
QT_TRANSLATE_NOOP::tr("paginate: true")
QT_TRANSLATE_NOOP::tr("style: |")
QT_TRANSLATE_NOOP::tr("section{")
QT_TRANSLATE_NOOP::tr("width: 32cm;")
QT_TRANSLATE_NOOP::tr("height: 19cm;")
QT_TRANSLATE_NOOP::tr("justify-content: flex-start;")
QT_TRANSLATE_NOOP::tr("}")
QT_TRANSLATE_NOOP::tr("section.lead h6 {text-align: bottom;}")
QT_TRANSLATE_NOOP::tr("section.lead header {font-weight: bold;}")
QT_TRANSLATE_NOOP::tr("3d slicer logo")
QT_TRANSLATE_NOOP::tr("3D Slicer")
QT_TRANSLATE_NOOP::tr("Data Loading and")
QT_TRANSLATE_NOOP::tr("<br>")
QT_TRANSLATE_NOOP::tr("Visualization Tutorial")
QT_TRANSLATE_NOOP::tr("<!-- footer: ![height:1.5cm](images/tinyPerk.jpg) ![height:1.5cm](images/tinyEbantica.jpg) "Laboratory for Percutaneous Surgery – Copyright © Queen’s University, 2022" ![height:1.5cm](images/tinySlicer.jpg) -->")
QT_TRANSLATE_NOOP::tr("Tutorial Dataset")
QT_TRANSLATE_NOOP::tr("Please download the following datasets:")
QT_TRANSLATE_NOOP::tr("https://github.com/PerkLab/PerkLabBootcamp/raw/master/Data/VisualizationTutorial_HeadScene.mrb")
QT_TRANSLATE_NOOP::tr("Main user interface")
QT_TRANSLATE_NOOP::tr("height:11cm")
QT_TRANSLATE_NOOP::tr("Load Sample MRI Data")
QT_TRANSLATE_NOOP::tr("height:11cm")
QT_TRANSLATE_NOOP::tr("Load Sample MRI Data")
QT_TRANSLATE_NOOP::tr("height:11cm")
QT_TRANSLATE_NOOP::tr("<!-- _class: lead -->")
QT_TRANSLATE_NOOP::tr("bg right height:11cm")
QT_TRANSLATE_NOOP::tr("Load Sample MRI Data")
QT_TRANSLATE_NOOP::tr("The axial, sagittal, and coronal views automatically show  the loaded volume")
QT_TRANSLATE_NOOP::tr("Adjust window/level")
QT_TRANSLATE_NOOP::tr("bg right height:11cm")
QT_TRANSLATE_NOOP::tr("Switch to window/level mouse mode")
QT_TRANSLATE_NOOP::tr("Adjust window/level")
QT_TRANSLATE_NOOP::tr("bg right height:11cm")
QT_TRANSLATE_NOOP::tr("Adjust window/level (brightness/contrast) using the left mouse button on a slice view")
QT_TRANSLATE_NOOP::tr("Switch back to view/transform mode")
QT_TRANSLATE_NOOP::tr("height:11cm")
QT_TRANSLATE_NOOP::tr("Maximize view")
QT_TRANSLATE_NOOP::tr("height:11cm")
QT_TRANSLATE_NOOP::tr("Slice view options")
QT_TRANSLATE_NOOP::tr("bg right height:11cm")
QT_TRANSLATE_NOOP::tr("Position your mouse cursor over the pin icon to display the slice view toolbar")
QT_TRANSLATE_NOOP::tr("Slice view options")
QT_TRANSLATE_NOOP::tr("bg right height:11cm")
QT_TRANSLATE_NOOP::tr("Once the slice viewer toolbar is shown, click on the “>>”.")
QT_TRANSLATE_NOOP::tr("Show ruler")
QT_TRANSLATE_NOOP::tr("height:11cm")
QT_TRANSLATE_NOOP::tr("Rotate to volume plane")
QT_TRANSLATE_NOOP::tr("bg right height:11cm")
QT_TRANSLATE_NOOP::tr("Often, MRI volumes are not axis-aligned. To show the true axial view, click the")
QT_TRANSLATE_NOOP::tr("‘Rotate to volume plane’")
QT_TRANSLATE_NOOP::tr("button.")
QT_TRANSLATE_NOOP::tr("Note: This image will not be affected, but many DICOM MR images need to be aligned.")
QT_TRANSLATE_NOOP::tr("Switch to conventional layout")
QT_TRANSLATE_NOOP::tr("height:11cm")
QT_TRANSLATE_NOOP::tr("Link views")
QT_TRANSLATE_NOOP::tr("bg right height:11cm")
QT_TRANSLATE_NOOP::tr("After linking views, if any setting is changed in a 2D view, all others follow.")
QT_TRANSLATE_NOOP::tr("Show slices in 3D")
QT_TRANSLATE_NOOP::tr("bg right height:11cm")
QT_TRANSLATE_NOOP::tr("Now the slice views are linked. If you click the")
QT_TRANSLATE_NOOP::tr("‘Toggle slice visibility in 3D view’")
QT_TRANSLATE_NOOP::tr("button, then all slices will show up.")
QT_TRANSLATE_NOOP::tr("Show slices in 3D")
QT_TRANSLATE_NOOP::tr("bg right height:11cm")
QT_TRANSLATE_NOOP::tr("All three anatomical slices are shown in the 3D view.")
QT_TRANSLATE_NOOP::tr("Navigating the 3D view")
QT_TRANSLATE_NOOP::tr("bg right height:11cm")
QT_TRANSLATE_NOOP::tr("Use the left mouse button to")
QT_TRANSLATE_NOOP::tr("rotate")
QT_TRANSLATE_NOOP::tr(", and the right mouse button to")
QT_TRANSLATE_NOOP::tr("zoom")
QT_TRANSLATE_NOOP::tr("in and out.")
QT_TRANSLATE_NOOP::tr("Close the scene")
QT_TRANSLATE_NOOP::tr("height:11cm")
QT_TRANSLATE_NOOP::tr("Part 2: 3D visualization of surface models of the brain")
QT_TRANSLATE_NOOP::tr("height:11cm")
QT_TRANSLATE_NOOP::tr("Load tutorial scene")
QT_TRANSLATE_NOOP::tr("bg right height:11cm")
QT_TRANSLATE_NOOP::tr("Drag and drop the file VisualizationTutorial")
QT_TRANSLATE_NOOP::tr("_")
QT_TRANSLATE_NOOP::tr("HeadScene.mrb into Slicer, then click")
QT_TRANSLATE_NOOP::tr("OK")
QT_TRANSLATE_NOOP::tr(".")
QT_TRANSLATE_NOOP::tr("Center view")
QT_TRANSLATE_NOOP::tr("bg right height:11cm")
QT_TRANSLATE_NOOP::tr("Click on the small box icon to center the view, in 3D or in 2D")
QT_TRANSLATE_NOOP::tr("Explore loaded data")
QT_TRANSLATE_NOOP::tr("bg right height:11cm")
QT_TRANSLATE_NOOP::tr("You can use the module list, or the favorite module toolbar to switch to the")
QT_TRANSLATE_NOOP::tr("Data module")
QT_TRANSLATE_NOOP::tr("Explore loaded data")
QT_TRANSLATE_NOOP::tr("bg right height:11cm")
QT_TRANSLATE_NOOP::tr("The Data module shows all the data in the scene.")
QT_TRANSLATE_NOOP::tr("The data items (“nodes”) can be shown/hidden, renamed, deleted, cloned, etc.")
QT_TRANSLATE_NOOP::tr("Hide the")
QT_TRANSLATE_NOOP::tr("‘skin’")
QT_TRANSLATE_NOOP::tr("model by clicking the eye icon.")
